import { jsPDF } from "jspdf";
import type { Contrat, Logement, Paiement } from "@/lib/api";

// --- FORMATTERS ---
function money(value: number | string): string {
  const amount = typeof value === "number" ? value : Number.parseFloat(value || "0");
  return new Intl.NumberFormat("fr-MA", { maximumFractionDigits: 0 }).format(Number.isFinite(amount) ? amount : 0);
}

function date(value: string | null, fallback = "Open"): string {
  if (!value) return fallback;
  return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(value));
}

// --- LOGO HANDLING ---
const LOGO_PATH = "/assets/profile/logo/immoflow-logo.png"; 

// --- UI COMPONENTS ---
function addHeader(doc: jsPDF, title: string, ref: string) {
  // 1. Add Logo Image
  try {
    // Parameters: (ImagePath, Format, X-position, Y-position, Width, Height)
    // FIX: Changed from 100x40 to 80x30 to prevent the horizontal stretching!
    doc.addImage(LOGO_PATH, "PNG", 40, 30, 80, 30, "", "MEDIUM");
  } catch (e) {
    console.warn("Logo image not found at path, falling back to text.");
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("IMMOFLOW", 40, 55);
  }

  // 2. Company Subtitle
  doc.setTextColor(100, 116, 139); // slate-500
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Premium Property Management", 40, 75);

  // 3. Document Details (Right Aligned)
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(title.toUpperCase(), 555, 55, { align: "right" });

  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Reference: ${ref}`, 555, 71, { align: "right" });
  doc.text(`Date: ${date(new Date().toISOString())}`, 555, 85, { align: "right" });

  // 4. Subtle Separator Line
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(1);
  doc.line(40, 110, 555, 110);
}

function addRow(doc: jsPDF, y: number, label: string, value: string, isLast = false) {
  // Label (Muted color)
  doc.setTextColor(100, 116, 139); // slate-500
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(label, 60, y);

  // Value (Bold Dark)
  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(value, 200, y, { maxWidth: 330 });

  // Subtle dividing line between rows
  if (!isLast) {
    doc.setDrawColor(241, 245, 249); // slate-100
    doc.setLineWidth(1);
    doc.line(60, y + 14, 535, y + 14);
  }
}

function addFooter(doc: jsPDF) {
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(1);
  doc.line(40, 780, 555, 780);

  doc.setTextColor(148, 163, 184); // slate-400
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Generated by ImmoFlow Platform. Securing better management.", 297, 805, { align: "center" });
}

// --- EXPORT FUNCTIONS ---

export function downloadContractPdf(contract: Contrat, property?: Logement | null): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  
  addHeader(doc, "Lease Agreement", `CTR-${String(contract.id).padStart(4, "0")}`);

  // Section Title
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Agreement Details", 40, 150);

  let y = 180;
  addRow(doc, y, "Property", property?.adresse ?? contract.logement.adresse); y += 35;
  addRow(doc, y, "Property Type", property?.type_logement.nom_type ?? "Property"); y += 35;
  addRow(doc, y, "Surface Area", property ? `${property.superficie} m²` : "Not specified"); y += 35;
  addRow(doc, y, "Tenant", `${contract.locataire.user.name} (${contract.locataire.user.email})`); y += 35;
  addRow(doc, y, "Agent", `${contract.agent.user.name} (${contract.agent.user.email})`); y += 35;
  addRow(doc, y, "Lease Period", `${date(contract.date_debut)}  —  ${date(contract.date_fin)}`); y += 35;
  addRow(doc, y, "Monthly Rent", `${money(contract.montant)} MAD`, true);

  // Signatures Section
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Signatures", 40, 480);

  // Modern Side-by-Side Signature Areas
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(1);

  // Left Box: Agent
  doc.roundedRect(40, 500, 245, 110, 8, 8, "S");
  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Agent Signature", 55, 520);
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "italic");
  doc.text("Digitally verified.", 55, 565);

  // Right Box: Tenant
  doc.roundedRect(310, 500, 245, 110, 8, 8, "S");
  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.text("Tenant Signature", 325, 520);

  if (contract.signature_data) {
    doc.addImage(contract.signature_data, "PNG", 325, 530, 215, 70, "", "MEDIUM");
  } else {
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "italic");
    doc.text("Pending signature...", 325, 565);
  }

  addFooter(doc);
  doc.save(`Lease_Agreement_CTR-${contract.id}.pdf`);
}

export function downloadReceiptPdf(payment: Paiement): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  
  addHeader(doc, "Payment Receipt", `PAY-${String(payment.id).padStart(4, "0")}`);

  // Big "Amount Paid" Hero Block
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(40, 140, 515, 100, 8, 8, "FD");

  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("AMOUNT PAID", 297, 175, { align: "center" });

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.text(`${money(payment.montant)} MAD`, 297, 210, { align: "center" });

  // Details Section Title
  doc.setFontSize(14);
  doc.text("Payment Summary", 40, 280);

  let y = 310;
  addRow(doc, y, "Received From", payment.contrat.locataire.user.name); y += 35;
  addRow(doc, y, "For Property", payment.contrat.logement.adresse); y += 35;
  addRow(doc, y, "Payment Date", date(payment.date_paiement)); y += 35;
  addRow(doc, y, "Payment Method", payment.mode); y += 35;
  addRow(doc, y, "Status", payment.statut.toUpperCase()); y += 35;
  addRow(doc, y, "Reference / Note", payment.reference ?? payment.rib ?? payment.cash_note ?? "N/A", true);

  // Final Thank You
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(12);
  doc.text("Thank you for choosing ImmoFlow.", 297, 560, { align: "center" });

  addFooter(doc);
  doc.save(`Payment_Receipt_PAY-${payment.id}.pdf`);
}