import { jsPDF } from "jspdf";
import type { Contrat, Logement, Paiement } from "@/lib/api";

function money(value: number | string): string {
  const amount = typeof value === "number" ? value : Number.parseFloat(value || "0");
  return new Intl.NumberFormat("fr-MA", { maximumFractionDigits: 0 }).format(Number.isFinite(amount) ? amount : 0);
}

function date(value: string | null, fallback = "Open"): string {
  if (!value) return fallback;
  return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(value));
}

function header(doc: jsPDF, title: string, ref: string): void {
  doc.setFillColor(23, 20, 17);
  doc.rect(0, 0, 595, 118, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("ImmoFlow", 48, 52);
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text(title, 48, 76);
  doc.text(ref, 410, 52);
  doc.text(date(new Date().toISOString()), 410, 76);
}

function row(doc: jsPDF, y: number, label: string, value: string): void {
  doc.setTextColor(120, 116, 110);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(label, 72, y);
  doc.setTextColor(23, 20, 17);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(value, 220, y, { maxWidth: 280 });
}

export function downloadContractPdf(contract: Contrat, property?: Logement | null): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  header(doc, "Rental contract", `CTR-${String(contract.id).padStart(4, "0")}`);

  doc.setFillColor(250, 247, 241);
  doc.roundedRect(48, 155, 499, 270, 16, 16, "F");
  row(doc, 195, "Property", property?.adresse ?? contract.logement.adresse);
  row(doc, 225, "Type", property?.type_logement.nom_type ?? "Property");
  row(doc, 255, "Surface", property ? `${property.superficie} m²` : "Not specified");
  row(doc, 285, "Tenant", `${contract.locataire.user.name} • ${contract.locataire.user.email}`);
  row(doc, 315, "Agent", `${contract.agent.user.name} • ${contract.agent.user.email}`);
  row(doc, 345, "Period", `${date(contract.date_debut)} to ${date(contract.date_fin)}`);
  row(doc, 375, "Monthly rent", `${money(contract.montant)} MAD`);
  row(doc, 405, "Signature status", contract.signature_status);

  doc.setTextColor(23, 20, 17);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Tenant signature", 48, 480);
  doc.setDrawColor(220, 218, 212);
  doc.roundedRect(48, 500, 240, 96, 12, 12, "S");

  if (contract.signature_data) {
    doc.addImage(contract.signature_data, "PNG", 70, 514, 190, 62);
  } else {
    doc.setTextColor(120, 116, 110);
    doc.setFont("helvetica", "normal");
    doc.text("Not signed yet", 72, 550);
  }

  doc.setTextColor(120, 116, 110);
  doc.setFontSize(10);
  doc.text("This document was generated from ImmoFlow dashboard data.", 48, 650);
  doc.save(`contract-${contract.id}.pdf`);
}

export function downloadReceiptPdf(payment: Paiement): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  header(doc, "Payment receipt", `PAY-${String(payment.id).padStart(4, "0")}`);

  doc.setFillColor(250, 250, 249);
  doc.roundedRect(48, 155, 499, 250, 16, 16, "F");
  row(doc, 195, "Tenant", payment.contrat.locataire.user.name);
  row(doc, 225, "Property", payment.contrat.logement.adresse);
  row(doc, 255, "Amount", `${money(payment.montant)} MAD`);
  row(doc, 285, "Date", date(payment.date_paiement));
  row(doc, 315, "Mode", payment.mode);
  row(doc, 345, "Status", payment.statut);
  row(doc, 375, "Reference", payment.reference ?? payment.rib ?? payment.cash_note ?? "Not provided");

  doc.setFillColor(134, 98, 52);
  doc.roundedRect(48, 465, 499, 54, 14, 14, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Receipt generated by ImmoFlow", 72, 497);
  doc.save(`payment-${payment.id}.pdf`);
}
