import { jsPDF } from "jspdf";
import type { Contrat, Logement, Paiement } from "@/lib/api";

type InvoiceInput = {
  ref: string;
  logement: Logement;
  contract: Contrat;
  payments?: Paiement[];
  issuerName: string;
  issuerEmail: string;
};

function money(value: number | string): string {
  const amount = typeof value === "number" ? value : Number.parseFloat(value || "0");

  return new Intl.NumberFormat("fr-MA", {
    maximumFractionDigits: 0,
  }).format(Number.isFinite(amount) ? amount : 0);
}

function shortDate(value: string | null): string {
  if (!value) {
    return "Open";
  }

  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(new Date(value));
}

export function downloadInvoicePdf({
  ref,
  logement,
  contract,
  payments = [],
  issuerName,
  issuerEmail,
}: InvoiceInput): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const paidTotal = payments
    .filter((payment) => payment.statut.toLowerCase() === "paid")
    .reduce((total, payment) => total + Number.parseFloat(payment.montant || "0"), 0);
  const rent = Number.parseFloat(contract.montant || logement.loyer || "0");
  const balance = Math.max(0, rent - paidTotal);
  const invoiceNumber = `INV-${ref.replace("PRP-", "")}-${new Date().getFullYear()}`;

  doc.setFillColor(23, 20, 17);
  doc.rect(0, 0, 595, 138, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("ImmoFlow", 48, 58);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Rental invoice", 48, 82);
  doc.text(invoiceNumber, 410, 58);
  doc.text(shortDate(new Date().toISOString()), 410, 82);

  doc.setTextColor(23, 20, 17);
  doc.setFillColor(246, 246, 244);
  doc.roundedRect(48, 170, 499, 104, 14, 14, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(logement.titre || logement.adresse, 72, 204, { maxWidth: 300 });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 86, 80);
  doc.text(`${logement.adresse} • ${logement.commune.nom}`, 72, 226, { maxWidth: 300 });
  doc.text(`${logement.type_logement.nom_type} • ${logement.superficie} m²`, 72, 246);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(23, 20, 17);
  doc.text(`${money(contract.montant)} MAD`, 390, 214);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90, 86, 80);
  doc.text("Monthly rent", 390, 236);

  doc.setDrawColor(228, 226, 221);
  doc.line(48, 315, 547, 315);
  doc.setTextColor(23, 20, 17);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Tenant", 48, 348);
  doc.text("Manager", 320, 348);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90, 86, 80);
  doc.text(contract.locataire.user.name, 48, 371);
  doc.text(contract.locataire.user.email, 48, 389);
  doc.text(issuerName, 320, 371);
  doc.text(issuerEmail, 320, 389);

  doc.setTextColor(23, 20, 17);
  doc.setFont("helvetica", "bold");
  doc.text("Contract terms", 48, 440);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90, 86, 80);
  doc.text(`Start: ${shortDate(contract.date_debut)}`, 48, 464);
  doc.text(`End: ${shortDate(contract.date_fin)}`, 180, 464);
  doc.text(`Status: ${contract.statut}`, 312, 464);

  doc.setFillColor(250, 250, 249);
  doc.roundedRect(48, 500, 499, 92, 12, 12, "F");
  doc.setFont("helvetica", "bold");
  doc.setTextColor(23, 20, 17);
  doc.text("Payment summary", 72, 532);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90, 86, 80);
  doc.text(`Paid: ${money(paidTotal)} MAD`, 72, 558);
  doc.text(`Balance: ${money(balance)} MAD`, 240, 558);
  doc.text(`Confirmation: ${balance === 0 ? "Complete" : "Tenant approval or payment pending"}`, 72, 578);

  doc.setFillColor(134, 98, 52);
  doc.roundedRect(48, 642, 499, 54, 14, 14, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Professional rental invoice generated by ImmoFlow", 72, 674);

  doc.save(`${invoiceNumber.toLowerCase()}.pdf`);
}
